// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace TumbleNet.CookieClicker.GooglePlay
{
public static class GPGSIds
{
        public const string achievement_get_the_game = "CgkIjKydt8kGEAIQBg"; // <GPGSID>
        public const string achievement_there_are_no_facts_only_interpretations = "CgkIjKydt8kGEAIQCg"; // <GPGSID>
        public const string achievement_money_money_money = "CgkIjKydt8kGEAIQCQ"; // <GPGSID>
        public const string leaderboard_number_of_cookies_sold = "CgkIjKydt8kGEAIQAw"; // <GPGSID>
        public const string achievement_whos_buying_cookies_now = "CgkIjKydt8kGEAIQCA"; // <GPGSID>
        public const string leaderboard_cookie_count = "CgkIjKydt8kGEAIQBA"; // <GPGSID>
        public const string achievement_you_have_to_start_somewhere = "CgkIjKydt8kGEAIQBw"; // <GPGSID>
        public const string leaderboard_coin_count = "CgkIjKydt8kGEAIQBQ"; // <GPGSID>

}
}
